import pandas as pd
from snakemake.utils import validate, min_version
from .fileutils import _get_seek_config
##### set minimum snakemake version #####
min_version("5.1.2")


##### load config and sample sheets #####

configfile: _get_seek_config()
validate(config, schema="schemas/config.schema.yaml")

subjects = pd.read_table(config["subjects"]).set_index("subject", drop=False)
validate(subjects, schema="schemas/subjects.schema.yaml")


##### target rules #####

rule all:
    input:
        expand(["results/diffexp/{contrast}.diffexp.tsv",
                "results/diffexp/{contrast}.ma-plot.svg"],
               contrast=config["diffexp"]["contrasts"]),
        "results/pca.svg",
        "qc/multiqc_report.html"


##### setup singularity #####

# this container defines the underlying OS for each job when using the workflow
# with --use-singularity
singularity: "docker://neuroseek/seek"


##### setup report #####

report: "report/workflow.rst"


##### load rules #####

include: "01-prep/prep.smk"
include: "02-reconstruction/reconstruction.smk"
include: "03-coregistration/coregistration.smk"
include: "04-contact_localization/contact_localization.smk"
include: "05-visualization/visualization.smk"
include: "06-postsurgery/postsurgery.smk"
include: "07-group_analysis/groups.smk"