import os
import sys
sys.path.append("../../../")
from neuroimg.pipeline.fileutils import SCRIPTS_UTIL_DIR
from neuroimg.pipeline.fileutils import get_freesurfer_patient_dir, get_freesurfer_dir, \
    get_rawct_dir, get_rawmri_dir, get_rawacpc_dir

"""
export SUBJECTS_DIR=~/hdd/data/neuroimaging/freesurfer_output/

A snakemake file for running reconstructions on the neuroimaging data.

snakemake --dag | dot -Tpdf > dag_pipeline_reconstruction.pdf

Runs tests to ensure data is all in the corresponding format: BIDS iEEG

If this doesn't work off the bat, make sure you explicitly set SUBJECTS_DIR
"""
configfile: "../config/localconfig.yaml"

# get the freesurfer patient directory
FS_OUTPUT_DIR = get_freesurfer_dir(config)
FS_PATIENT_OUTPUT_DIR = get_freesurfer_patient_dir(config)
RAW_CT_FOLDER = get_rawct_dir(config)
RAW_MRI_FOLDER = get_rawmri_dir(config)
RAW_MRIACPC_FOLDER = get_rawacpc_dir(config)

FSOUT_MRI_FOLDER = os.path.join(FS_PATIENT_OUTPUT_DIR, "mri")
FSOUT_CT_FOLDER = os.path.join(FS_PATIENT_OUTPUT_DIR, "CT")
FSOUT_ELECS_FOLDER = os.path.join(FS_PATIENT_OUTPUT_DIR, "elecs")
FSOUT_ACPC_FOLDER = os.path.join(FS_PATIENT_OUTPUT_DIR, "acpc")
FSOUT_SURF_FOLDER = os.path.join(FS_PATIENT_OUTPUT_DIR, "surf")

# First rule
rule all:
    input:
        outsuccess_file=expand(os.path.join(FS_PATIENT_OUTPUT_DIR, "{patient_id}_recon_success.txt"),
                               patient_id=config['patients']),
        brainmask_nifti = expand(os.path.join(FSOUT_MRI_FOLDER, "brainmask.nii.gz"),
                               patient_id=config['patients']),
        lhpial = expand(os.path.join(FSOUT_SURF_FOLDER, "ascii", "lh.pial.asc"),
                                patient_id=config['patients']),
        rhpial = expand(os.path.join(FSOUT_SURF_FOLDER, "ascii", "rh.pial.asc"),
                                patient_id=config['patients']),
        subcort_success_flag_file = expand(os.path.join(FS_PATIENT_OUTPUT_DIR, "{patient_id}_subcort_success.txt"),
                                patient_id=config['patients']),
        MRI_NIFTI_IMG = expand(os.path.join(FSOUT_MRI_FOLDER, "origT1.nii"),
                               patient_id=config['patients']),
    shell:
        "echo 'done'"


"""
Rule for prepping fs_recon.

The purpose is to setup a directory file structure that plays nice w/ Freesurfer. If you are using
some other module it is recommended to just add directories in there.

Rule for converting .dicom -> .niftiPUT_DIR,
                            "lh.native.aparc.annot"),
        rhlabel=os.path.join(NATIVESPACE_OUTPUT_DIR,
                            "rh.native.aparc.annot"),

"""
rule prep_recon:
    params:
        fs_subj_dir = os.path.join(FS_PATIENT_OUTPUT_DIR),
        CT_FOLDER=RAW_CT_FOLDER,
        MRI_FOLDER=RAW_MRI_FOLDER,
        CTDIR = FSOUT_CT_FOLDER,
        elecsdir = FSOUT_ELECS_FOLDER,
        acpcdir = FSOUT_ACPC_FOLDER,
        INPUT_FS_ORIG_DIR = os.path.join(FSOUT_MRI_FOLDER, "orig"),
        MRI_MGZ_IMG=os.path.join(FSOUT_MRI_FOLDER, "orig", "001.mgz"),
    output:
        CT_NIFTI_IMG=os.path.join(FSOUT_CT_FOLDER, "CT.nii"),
        MRI_NIFTI_IMG = os.path.join(FS_PATIENT_OUTPUT_DIR, "mri", "origT1.nii")
    shell:
        "mkdir -p {params.CTDIR};"
        "mkdir -p {params.elecsdir};"
        "mkdir -p {params.acpcdir};"
        "mkdir -p {params.INPUT_FS_ORIG_DIR};"
        "mrconvert {params.CT_FOLDER} {output.CT_NIFTI_IMG};"
        "mrconvert {params.MRI_FOLDER} {params.MRI_MGZ_IMG}; "
        "mrconvert {params.MRI_MGZ_IMG} {output.MRI_NIFTI_IMG};"

rule convert_nifti:
    params:
        MRI_FOLDER=RAW_MRI_FOLDER,
        MRI_NIFTI_IMG = os.path.join(FSOUT_MRI_FOLDER, "orig", "001.nii"),
    output:
        MRI_MGZ_IMG = os.path.join(FSOUT_MRI_FOLDER, "orig", "001.mgz"),
    shell:
        "mrconvert {params.MRI_FOLDER} {params.MRI_NIFTI_IMG};"
        "mrconvert {params.MRI_NIFTI_IMG} {output.MRI_MGZ_IMG};"
        "rm {params.MRI_NIFTI_IMG};"

"""
Use ACPC aligned T1 image. Comment out if not using.
"""
# rule use_acpc_specified_input:
#     params:
#         ACPC_IMAGE = os.path.join(RAW_MRIACPC_FOLDER, "{patient_id}_MR_acpc.nii"),
#     output:
#         FS_ACPC_IMAGE = os.path.join(FSOUT_ACPC_FOLDER, "{patient_id}_MR_acpc.nii"),
#         MRI_MGZ_IMG = os.path.join(FSOUT_MRI_FOLDER, "orig", "001.mgz"),
#     shell:
#         "cp {params.ACPC_IMAGE} {output.FS_ACPC_IMAGE};"
#         "mrconvert {input.FS_ACPC_IMAGE} {output.MRI_MGZ_IMG};"


"""
TODO: Rule to run more then one MRI/CT Scan for Movement Correction.

Converts another folder into more scans. WIP.
"""
rule add_scans_for_subj:
    params:
        fs_subj_dir = FS_PATIENT_OUTPUT_DIR,
        MRI_FOLDER=os.path.join(FS_PATIENT_OUTPUT_DIR, "premri2"),
        MRI1_NIFTI_IMG = os.path.join(FSOUT_MRI_FOLDER, "T1.nii")
    output:
        MRI_MGZ_IMG=os.path.join(FSOUT_MRI_FOLDER, "orig", "002.mgz"),
        MRI_NIFTI_IMG = os.path.join(FSOUT_MRI_FOLDER, "origT1_2.nii"),
        MRI_CONFORMED_NIFTI_IMG = os.path.join(FS_PATIENT_OUTPUT_DIR, "mri", "T1_2conform.nii.gz")
    shell:
        "mrconvert {params.MRI_FOLDER} {output.MRI_NIFTI_IMG};"
        "flirt -in {output.MRI_NIFTI_IMG} -ref {params.MRI1_NIFTI_IMG} -out {output.MRI_CONFORMED_NIFTI_IMG};"
        "mrconvert {output.MRI_CONFORMED_NIFTI_IMG} {output.MRI_MGZ_IMG};"


"""
Rule for reconstructions .nifti -> output files.

Since Freesurfer creates the directory on its own + snakemake does too,
I instead specify an output as a "temporary" flagger file that will let snakemake
know that reconstruction was completed.
"""
rule reconstruction:
    input:
        MRI_MGZ_IMG = os.path.join(FSOUT_MRI_FOLDER, "orig", "001.mgz"),
    params:
        patient="{patient_id}",
        SUBJECTS_DIR=FS_OUTPUT_DIR,
    output:
        outsuccess_file=os.path.join(FS_PATIENT_OUTPUT_DIR, "{patient_id}_recon_success.txt")
    shell:
        "echo 'hi';"
        "export SUBJECTS_DIR={params.SUBJECTS_DIR};" \
        "SUBJECTS_DIR={params.SUBJECTS_DIR};"
        # "recon-all " \
        #     "-cw256 " \
        #     "-i {input.MRI_MGZ_IMG} " \
        #     "-subjid {params.patient} " \
        #     "-all "\
        #     "-parallel -openmp 4;"
        "touch {output.outsuccess_file}"

"""
Rule for converting the pial surfaces to ascii data, so that it is readable by python/matlab.
"""
rule convert_pial_surface_files_ascii:
    input:
        outsuccess_file=os.path.join(FS_PATIENT_OUTPUT_DIR, "{patient_id}_recon_success.txt")
    params:
        lhpial = os.path.join(FSOUT_SURF_FOLDER, "lh.pial"),
        rhpial = os.path.join(FSOUT_SURF_FOLDER, "rh.pial"),
    output:
        lhpial=os.path.join(FSOUT_SURF_FOLDER, "ascii", "lh.pial.asc"),
        rhpial=os.path.join(FSOUT_SURF_FOLDER, "ascii", "rh.pial.asc"),
    shell:
        "mris_convert {params.lhpial} {output.lhpial};"
        "mris_convert {params.rhpial} {output.rhpial};"

"""
Rule for converting brainmask image volume from MGZ to Nifti.
"""
rule convert_brainmask_to_nifti:
    input:
        outsuccess_file = os.path.join(FS_PATIENT_OUTPUT_DIR, "{patient_id}_recon_success.txt")
    params:
        brainmask_mgz = os.path.join(FSOUT_MRI_FOLDER, "brainmask.mgz")
    output:
        brainmask_nifti = os.path.join(FSOUT_MRI_FOLDER, "brainmask.nii.gz")
    shell:
        "mri_convert {params.brainmask_mgz} {output.brainmask_nifti};"

"""
Rule for extracting the subcortical regions

- creates a new folder aseg2srf inside the fs_output data directory
- c/p this into our final result directory
"""
rule create_subcortical_volume:
    input:
        outsuccess_file = os.path.join(FS_PATIENT_OUTPUT_DIR, "{patient_id}_recon_success.txt")
    params:
        fs_dir = FS_OUTPUT_DIR,
        patient="{patient_id}",
        scripts_dir=SCRIPTS_UTIL_DIR,
    output:
        subcort_success_flag_file=os.path.join(FS_PATIENT_OUTPUT_DIR, "{patient_id}_subcort_success.txt"),
    shell:
        # generate subcortical region volume bounding surfaces
        "export SUBJECTS_DIR={params.fs_dir};"
        "SUBJECTS_DIR={params.fs_dir};"
        "{params.scripts_dir}/aseg2srf -s {params.patient};"
        "touch {output.subcort_success_flag_file};"


