import snakemake
import os

"""
export SUBJECTS_DIR=~/hdd/data/neuroimaging/freesurfer_output/

A snakemake file for running reconstructions on the neuroimaging data.

snakemake --dag | dot -Tpdf > dag_neuroimaging_pipeline_reconstruction.pdf

Runs tests to ensure data is all in the corresponding format:

0. patient (raw)
    - premri
        - (list) dicoms
    - postct
        - (list) dicoms
    - dti
        - (list) dicoms

0b. freesurfer_output / reconstruction_output
    - patient (reconstruction)
        - (tree) files
    - finaloutput_datadir (stores all files we want to use in the next step)
    - success_file_flag.txt
    - stick all raw file

1. patient (processed)
    - mri
        - nifti volume image
    - ct
        - nifti volume image
    - dti (optional)
        - nifti volume image
    - elec
        - ct_in_t1_volume image
        - chans_xyz.txt
    - surface (how to draw out the brain; )
        - triangles.txt
        - vertices.txt
        - normals.txt
        - voxel_xyz.txt
    - parcellation (depends on atlas)
        -<atlas_1>
            - region_mapping_cort_<atlas>.txt
            - region_mapping_subcort_<atlas>.txt
            - region_centres_<atlas>.txt
            - region_areas_<atlas>.txt
            - region_cortical_<atlas>.txt
            - region_average_orientations_<atlas>.txt
            - label_in_T1_<atlas> volume image (maps all voxels to an atlas region)
    - connectome (depends on atlas)
        - tract_lengths_<atlas>.txt
        - weights_<atlas>.txt
        - gain_mat_<atlas>.txt (how to project regional activity -> sensor space | mainly for TVB)
    - seeg
        - edf
        - fif
    - scalp
        - edf
        - fif
    - clinical
        - ez_hypothesis_chans.txt
        - ez_hypothesis_<atlas>.txt
        - stores clinical metadata
        - PPTs related
    TUTORIAL_FILE.TXT

If this doesn't work off the bat, make sure you explicitly set SUBJECTS_DIR
"""
configfile: "../config/localconfig.yaml"
snakemake.utils.validate(config, "../config/preformat_config.schema.yaml")

# os.putenv('SUBJECTS_DIR', config['fs_outputdatadir']); os.system('bash')"

# get the environment variable for freesurfer - for use in getting access to lut's
FREESURFER_HOME = os.getenv("FREESURFER_HOME") or ''
MRTRIX3_HOME = os.getenv("MRTRIX3_HOME") or ''
HOME_DIR="../../"
SCRIPTS_UTIL_DIR = "../neuroimg/format/"
ATLAS=['dk', 'destrieux']

''' USER DEFINED DIRECTORIES TO STORE FINAL DATA IN ORGANIZED SUBFOLDERS '''
FS_PATIENT_OUTPUT_DIR = os.path.join(config['fs_outputdatadir'],
                                     "{patient_id}")

PATIENT_OUTPUT_DIR = os.path.join(config['finaloutput_datadir'],
                                        "{patient_id}")

parc = "aparc.a2009s"
aa = "aparc+aseg"
sval = "pial"
hemispheres = ['lh', 'rh']
resamp_target = "fsaverage5"

# print(config['patients'])

# First rule
rule all:
    input:
        lhpial = expand(os.path.join(PATIENT_OUTPUT_DIR,
                              "lh.pial.asc"),
                        patient_id=config['patients']),
    shell:
        "echo 'done'"



"""
Rule for converting .dicom -> .niftiPUT_DIR,
                            "lh.native.aparc.annot"),
        rhlabel=os.path.join(NATIVESPACE_OUTPUT_DIR,
                            "rh.native.aparc.annot"),

Assumes user has premri and postct with DTI being optional, as this is not standard clinical procedure
in the USA.
"""
rule dicom_to_nifti:
    params:
        CT_FOLDER=os.path.join(config['rawdatadir'],"{patient_id}", "postct"),
        MRI_FOLDER=os.path.join(config['rawdatadir'], "{patient_id}", "premri"),
    output:
        CT_NIFTI_IMG=os.path.join(config['finaloutput_datadir'],
                                        "{patient_id}",
                                         "CT.nii.gz"),
        MRI_NIFTI_IMG=os.path.join(config['finaloutput_datadir'],
                                        "{patient_id}",
                                          "T1.nii.gz")
    shell:
        "echo {params};"
        "mrconvert {params.CT_FOLDER} {output.CT_NIFTI_IMG};"
        "mrconvert {params.MRI_FOLDER} {output.MRI_NIFTI_IMG};"

"""
Rule to pre-setup the freesurfer output directory with the orig.mgz file
"""
rule pre_reconstruction:
    input:
        MRI_NIFTI_IMG=os.path.join(config['finaloutput_datadir'],
                                        "{patient_id}",
                                          "T1.nii.gz")
    params:
        patient="{patient_id}", # patient_id=config['patients']),
        SUBJECTS_DIR=os.path.join(config['fs_outputdatadir']),
    output:
        outmgz_file=os.path.join(config['fs_outputdatadir'],
                                     "{patient_id}",
                                    "mri/orig",
                                     "001.mgz")
    shell:
        "export SUBJECTS_DIR={params.SUBJECTS_DIR}; \
            SUBJECTS_DIR={params.SUBJECTS_DIR};"
        "mri_convert {params.MRI_NIFTI_IMG} {output.outmgz_file};"

"""
Rule for reconstructions .nifti -> output files.

Since Freesurfer creates the directory on its own + snakemake does too,
I instead specify an output as a "temporary" flagger file that will let snakemake
know that reconstruction was completed.
"""
rule reconstruction:
    input:
        MRI_NIFTI_IMG=os.path.join(PATIENT_OUTPUT_DIR,
                                          "T1.nii.gz")
    params:
        patient="{patient_id}",
        SUBJECTS_DIR=os.path.join(config['fs_outputdatadir']),
    output:
        outsuccess_file=os.path.join(config['fs_outputdatadir'],
                                "{patient_id}_recon_success.txt")
    shell:
        # "export SUBJECTS_DIR={params.SUBJECTS_DIR}; \
        #     SUBJECTS_DIR={params.SUBJECTS_DIR};"
        # "recon-all -i {input.MRI_NIFTI_IMG} \
        #     -subjid {params.patient} -all \
        #     -parallel -openmp 4;"
        "touch {output.outsuccess_file}"

"""
Rule to copy all necessary reconstruction files to a temporary directory,
so that we can explicitly say which files are being analyzed/used.

Add here files to copy them to the directory that we allow scripts to draw from.
"""
rule copy_reconstruction_files:
    input:
        outsuccess_file=os.path.join(config['fs_outputdatadir'],
                                "{patient_id}_recon_success.txt")
    params:
        lhpial=os.path.join(config['fs_outputdatadir'],
                            "{patient_id}",
                            "surf/lh.pial"),
        rhpial=os.path.join(config['fs_outputdatadir'],
                            "{patient_id}",
                            "surf/rh.pial"),
        lhlabel=os.path.join(config['fs_outputdatadir'],
                            "{patient_id}",
                            "label/lh.aparc.annot"),
        rhlabel=os.path.join(config['fs_outputdatadir'],
                            "{patient_id}",
                            "label/rh.aparc.annot"),
        aseg_output_file = os.path.join(config['fs_outputdatadir'],
                                        "{patient_id}",
                                        "mri/aseg.mgz"),
        norm_output_file = os.path.join(config['fs_outputdatadir'],
                                        "{patient_id}",
                                        "mri/norm.mgz"),
        aparc_dkatlas_aseg_file = os.path.join(config['fs_outputdatadir'],
                                                 "{patient_id}",
                                                "mri/aparc+aseg.mgz"),
        aparc_atlas_aseg_file = os.path.join(config['fs_outputdatadir'],
                                                 "{patient_id}",
                                                "mri/aparc.a2009s+aseg.mgz"),
        t1_mgz_file = os.path.join(config['fs_outputdatadir'],
                        "{patient_id}",
                        "mri/T1.mgz"),
        brainmask_file = os.path.join(config['fs_outputdatadir'],
                                      "{patient_id}",
                                      "mri/brainmask.mgz"),
        rawavg_file = os.path.join(config['fs_outputdatadir'],
                                      "{patient_id}",
                                      "mri/rawavg.mgz"),
        wm_output_file = os.path.join(config['fs_outputdatadir'],
                                      "{patient_id}",
                                      "mri/wm.mgz"),
        talairach_transform_file = os.path.join(config['fs_outputdatadir'],
                                                "{patient_id}",
                                                "mri/transforms/talairach.xfm")
    output:
        lhpial=os.path.join(PATIENT_OUTPUT_DIR,
                            "lh.pial"),
        rhpial=os.path.join(PATIENT_OUTPUT_DIR,
                            "rh.pial"),
        lhlabel=os.path.join(PATIENT_OUTPUT_DIR,
                            "lh.aparc.annot"),
        rhlabel=os.path.join(PATIENT_OUTPUT_DIR,
                            "rh.aparc.annot"),
        aseg_output_file = os.path.join(PATIENT_OUTPUT_DIR,
                                        "aseg.mgz"),
        norm_output_file = os.path.join(PATIENT_OUTPUT_DIR,
                                        "norm.mgz"),
        aparc_atlas_aseg_file = os.path.join(PATIENT_OUTPUT_DIR,
                                             "aparc.a2009s+aseg.mgz"),
        aparc_dkatlas_aseg_file = os.path.join(PATIENT_OUTPUT_DIR,
                                            "aparc+aseg.mgz"),
        t1_mgz_file = os.path.join(PATIENT_OUTPUT_DIR,
                                        "T1.mgz"),
        brainmask_file = os.path.join(PATIENT_OUTPUT_DIR,
                                      "brainmask.mgz"),
        wm_output_file = os.path.join(PATIENT_OUTPUT_DIR,
                                      "wm.mgz"),
        rawavg_file = os.path.join(PATIENT_OUTPUT_DIR,
                                   "rawavg.mgz"),
        talairach_transform_file = os.path.join(PATIENT_OUTPUT_DIR,
                                                "transforms/talairach.xfm")
    shell:
        "cp {params.lhpial} {output.lhpial};"
        "cp {params.rhpial} {output.rhpial};"
        "cp {params.lhlabel} {output.lhlabel};"
        "cp {params.rhlabel} {output.rhlabel};"
        "cp {params.aseg_output_file} {output.aseg_output_file};"
        "cp {params.norm_output_file} {output.norm_output_file};"
        "cp {params.aparc_atlas_aseg_file} {output.aparc_atlas_aseg_file};"
        "cp {params.aparc_dkatlas_aseg_file} {output.aparc_dkatlas_aseg_file};"
        "cp {params.t1_mgz_file} {output.t1_mgz_file};"

        "cp {params.brainmask_file} {output.brainmask_file};"
        "cp {params.rawavg_file} {output.rawavg_file};"
        "cp {params.wm_output_file} {output.wm_output_file};"

        "cp {params.talairach_transform_file} {output.talairach_transform_file};"

"""
Rule for converting the pial surfaces to ascii data, so that it is readable by python/matlab.
"""
rule convert_pial_surface_files:
    input:
        lhpial=os.path.join(PATIENT_OUTPUT_DIR,
                            "lh.pial"),
        rhpial=os.path.join(PATIENT_OUTPUT_DIR,
                            "rh.pial"),
        # lhpial_native = os.path.join(PATIENT_OUTPUT_DIR,
        #                       "lh_native.pial"),
        # rhpial_native = os.path.join(PATIENT_OUTPUT_DIR,
        #                       "rh_native.pial"),
    output:
        lhpial=os.path.join(PATIENT_OUTPUT_DIR,
                            "lh.pial.asc"),
        rhpial=os.path.join(PATIENT_OUTPUT_DIR,
                            "rh.pial.asc"),
        # lhpial_native = os.path.join(PATIENT_OUTPUT_DIR,
        #                       "lh_native.asc"),
        # rhpial_native = os.path.join(PATIENT_OUTPUT_DIR,
        #                       "rh_native.asc"),
    shell:
        "mris_convert {input.lhpial} {output.lhpial};"
        "mris_convert {input.rhpial} {output.rhpial};"
        # "mris_convert {input.lhpial_native} {output.lhpial_native};"
        # "mris_convert {input.rhpial_native} {output.rhpial_native};"


rule convert_to_nifti:
    input:
        brainmask_mgz = os.path.join(config['finaloutput_datadir'],
                                                     "{patient_id}",
                                                     "nativespace-transform",
                                     "brainmask_native.mgz")
    output:
        brainmask_nifti = os.path.join(config['finaloutput_datadir'],
                                                     "{patient_id}",
                                                     "nativespace-transform",
                                       "brainmask_native.nii.gz")
    shell:
        "mri_convert {input.brainmask_mgz} {output.brainmask_nifti};"

